name: flutter_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  country_picker: ^2.0.16
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_emoji: ^2.4.0
  flutter_svg: ^1.1.5
  freezed: ^2.1.0+1
  get_it: ^7.2.0
  image_picker: ^0.8.5+3
  internet_connection_checker: ^0.0.1+4
  json_serializable: ^6.3.2
  lottie: ^1.4.3
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.3+2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
